import {test} from 'node:test';import assert from 'node:assert/strict';
import {quantity,quantityList,averageKills,dropTrace,groupColor,pathGroupKey} from '../src/drop/display.js';
import {makeDropIndex} from '../server/drop-engine.mjs';
test('average kill counts use reciprocal expected selections, rounding, and explicit impossible/unknown states',()=>{assert.equal(averageKills(.05),'20마리');assert.equal(averageKills(.03),'33마리');assert.equal(averageKills(1),'1마리');assert.equal(averageKills(2),'1마리 미만');assert.equal(averageKills(0),'획득 불가');assert.equal(averageKills(null),'계산 불가');assert.equal(averageKills(NaN),'계산 불가');});
test('equal quantity ranges collapse without dropping distinct ranges',()=>{assert.equal(quantity(1,1),'1');assert.equal(quantity(1,3),'1–3');assert.equal(quantity(null,3),'—');assert.equal(quantityList('["1~1","2~5"]'),'1, 2–5');assert.equal(quantityList('[]'),'없음');});
test('source descriptions retain only Drop sheets in plain Korean',()=>{assert.equal(dropTrace('(Temp)NPC_Abil!175 (v34) → NPC_Abil!175 (v34) → Drop_Info!20 (v46)'),'Drop 엑셀 · Drop_Info 시트, 20행 (v46)');});
test('same group gets stable color across slots and distinct groups have varied pastel colors',()=>{assert.equal(pathGroupKey({kind:'그룹',groupId:'7',groupSlot:1}),pathGroupKey({kind:'그룹',groupId:'7',groupSlot:8}));assert.equal(groupColor('group:7'),groupColor('group:7'));assert.equal(new Set(Array.from({length:100},(_,i)=>groupColor('group:'+i))).size,100);});
test('unlinked Drop IDs sort after all NPCs before pagination, even with exact ID match',()=>{const dataset={format:1,tables:{infos:[{id:'12',groups:[],direct:[]}],npcs:[{id:'123',abilityId:'123'},{id:'124',abilityId:'124'}],abilities:[{id:'123',dropId:'0'},{id:'124',dropId:'0'}]}};const index=makeDropIndex(dataset);assert.deepEqual(index.search('12',0,100).rows.map(r=>r.id),['123','124','12']);assert.deepEqual(index.search('12',0,2).rows.map(r=>r.id),['123','124']);assert.equal(index.search('12',2,2).rows[0].kind,'table');});

test('presentation rounds percentages to four decimal places without changing input data',async()=>{const {decimal4,probabilityText,probabilityString}=await import('../src/drop/display.js');assert.equal(decimal4(1.23455),'1.2346');assert.equal(probabilityText(.012345678),'1.2346%');assert.equal(probabilityString('7.123456%'),'7.1235%');assert.equal(probabilityText(1),'100%');assert.equal(probabilityText(null),'계산 불가');});
test('unchanged difference and unchanged displayed kill counts share the same label',async()=>{const {probabilityDifference,averageKillChange}=await import('../src/drop/display.js');assert.equal(probabilityDifference(.05,.05),'차이 없음');assert.equal(averageKillChange(.05,.05),'차이 없음');assert.equal(averageKillChange(.05001,.05),'차이 없음');assert.equal(probabilityDifference(.05,.06),'+1 %p');assert.equal(averageKillChange(.05,.1),'20마리 → 10마리');assert.equal(probabilityDifference(null,null),'계산 불가');assert.notEqual(averageKillChange(null,null),'차이 없음');});
test('a rounded-away probability change is not called unchanged',async()=>{const {probabilityDifference}=await import('../src/drop/display.js');assert.equal(probabilityDifference(.05,.05000001),'0 %p (반올림)');});
