import {test} from 'node:test';import assert from 'node:assert/strict';
import {compareDrops} from '../server/drop-compare.mjs';
const r=(id,props={})=>({id:String(id),v:1,source:{sheet:'test',row:5,version:'v1'},...props});
function fixture(){return {format:1,registeredAt:'2026-09-17',referenceMetadataVersion:1,sources:[],tables:{
 infos:[r(1,{groups:[{slot:1,id:'20',rate:500000}],direct:[]}),r(2,{groups:[{slot:1,id:'20',rate:500000}],direct:[]})],groups:[r(20,{entries:[{slot:1,id:'30',rate:1000000}]})],drops:[r(30,{itemId:'40',min:1,max:1})],
 npcs:[r(1,{abilityId:'1'}),r(2,{abilityId:'2'})],abilities:[r(1,{dropId:'1',level:115}),r(2,{dropId:'2',level:115})],abilityNames:[r(1,{name:'몬스터 A'}),r(2,{name:'몬스터 B'})],npcNames:[1,2].map(id=>r(id,{uniqueNumber:'공통번호',map:'지역',area:'사냥터',npcType:'일반',displayLevel:'115'})),items:[r(40,{baseId:'50'})],bases:[r(50,{stringId:'60',grade:4})],strings:[r(60,{nameId:'70',titleId:'0'})],names:[r(70,{name:'검증 아이템'})]
 }};}
const onlyDrop=d=>({...d,tables:Object.fromEntries(['infos','groups','drops'].map(k=>[k,d.tables[k]]))});
const compare=(a,b,refs=a)=>compareDrops(onlyDrop(a),onlyDrop(b),refs);
test('identical files and physical row/version changes produce no semantic changes',()=>{const a=fixture(),b=structuredClone(a);b.tables.infos.reverse();b.tables.infos.forEach(x=>{x.v=100;x.source.row=500;});assert.equal(compare(a,b).count.changed,0);});
test('shared Drop_Group change propagates to every linked monster and groups rarity summaries',()=>{const a=fixture(),b=structuredClone(a);b.tables.groups[0].entries=[{slot:1,id:'30',rate:500000},{slot:2,id:'0',rate:500000}];const c=compare(a,b);assert.equal(c.count.changed,2);assert.equal(c.count.items,2);assert.equal(c.groups.length,1);assert.match(c.groups[0].text,/희귀 등급 아이템의 드랍 확률이 하락/);assert.equal(c.details['1'].changes[0].oldChance,0.5);assert.equal(c.details['1'].changes[0].newChance,0.25);});
test('Drop_Item quantity changes propagate even if probability is unchanged',()=>{const a=fixture(),b=structuredClone(a);b.tables.drops[0].min=2;b.tables.drops[0].max=3;const c=compare(a,b);assert.equal(c.count.changed,2);assert.match(c.groups[0].text,/지급 수량이 증가/);assert.equal(c.details['1'].changes[0].direction,'other');});
test('slot reorder or replacement IDs with same outcome do not cause false differences',()=>{const a=fixture(),b=structuredClone(a);b.tables.infos.forEach(x=>{x.groups[0].slot=99;x.groups[0].id='21';});b.tables.groups[0].id='21';b.tables.groups[0].entries[0].slot=4;assert.equal(compare(a,b).count.changed,0);});
test('a guaranteed drop still detects additional independent draws',()=>{const a=fixture();a.tables.infos.forEach(x=>x.groups[0].rate=1000000);const b=structuredClone(a);b.tables.infos[0].groups.push({slot:2,id:'20',rate:500000});const c=compare(a,b);assert.equal(c.count.changed,1);assert.equal(c.details['1'].changes[0].newChance,1);assert.equal(c.details['1'].changes[0].newExpected,1.5);});
test('added and removed items are distinct and missing names use IDs',()=>{const a=fixture(),b=structuredClone(a);b.tables.drops[0].itemId='777';const c=compare(a,b);assert.deepEqual(c.details['1'].changes.map(x=>x.direction).sort(),['added','removed']);assert.equal(c.details['1'].changes.find(x=>x.itemId==='777').name,'777');});
test('all-zero paths are equal to absent paths',()=>{const a=fixture(),b=structuredClone(a);a.tables.infos.forEach(x=>x.groups[0].rate=0);b.tables.infos.forEach(x=>x.groups=[]);assert.equal(compare(a,b).count.changed,0);});
test('mixed directions remain mixed, same unique number but different areas stay separate',()=>{const a=fixture(),b=structuredClone(a);b.tables.infos[0].groups[0].rate=600000;b.tables.infos[1].groups[0].rate=400000;let c=compare(a,b);assert.match(c.groups[0].text,/확률이 상승[\s\S]*확률이 하락/);const refs=structuredClone(a);refs.tables.npcNames[1].area='다른 사냥터';assert.equal(compare(a,b,refs).groups.length,2);});
test('missing group becomes calculation error, never a fabricated zero',()=>{const a=fixture(),b=structuredClone(a);b.tables.groups=[];const c=compare(a,b);assert.equal(c.count.errors,2);assert.equal(c.details['1'].changes[0].newChance,null);assert.equal(c.details['1'].changes[0].direction,'error');assert.ok(c.details['1'].warnings.some(x=>x.includes('드랍 그룹 없음')));});
test('table additions/removals are recorded even for empty outcome tables',()=>{const a=fixture(),b=structuredClone(a);b.tables.infos.pop();const c=compare(a,b);assert.equal(c.count.removedMonsters,1);assert.equal(c.details['2'].status,'제거');});
test('common latest reference names and grades apply to both sides',()=>{const a=fixture(),b=structuredClone(a),refs=structuredClone(a);b.tables.infos[0].groups[0].rate=400000;refs.tables.names[0].name='최신 이름';refs.tables.bases[0].grade=7;const x=compare(a,b,refs).details['1'].changes[0];assert.equal(x.name,'최신 이름');assert.equal(x.gradeName,'신화');});
test('tiny nonzero changes are retained',()=>{const a=fixture(),b=structuredClone(a);a.tables.infos[0].groups[0].rate=1;b.tables.infos[0].groups[0].rate=2;for(const d of [a,b])d.tables.groups[0].entries=[{slot:1,id:'30',rate:1},{slot:2,id:'0',rate:999999}];const c=compare(a,b);assert.equal(c.details['1'].changes[0].direction,'increase');assert.equal(c.details['1'].changes[0].newChance,2e-12);});
