import {test} from 'node:test';import assert from 'node:assert/strict';
import {groupSummaries} from '../server/drop-summary.mjs';import {selectLatest} from '../server/drop-normalize.mjs';import {makeDropIndex} from '../server/drop-engine.mjs';
const change=(rate=.2)=>({itemId:'40',name:'아이템',grade:4,direction:'decrease',oldChance:.3,newChance:rate,quantityChanged:false,oldQuantity:'["1~1"]',newQuantity:'["1~1"]',oldExpected:.3,newExpected:rate});
const member=(id,rate=.2)=>({monster:{id,name:'몬스터 '+id,map:'SPECIAL_지역',area:'없음',npcType:'일반 몬스터',uniqueNumber:'공통',displayLevel:115,classificationSource:{sheet:'(Temp)NPC_Info',row:5,version:'v12'}},changes:[change(rate)]});
test('category summary counts unique items without item names or exact probabilities',()=>{const g=groupSummaries([member('1'),member('2')])[0];assert.equal(g.title,'지역');assert.equal(g.areaLabel,'미지정');assert.equal(g.rollups[0].monsterCount,2);assert.equal(g.rollups[0].itemCount,1);assert.equal(g.rollups[0].perMonsterMin,1);assert.match(g.text,/희귀 등급 아이템의 드랍 확률이 하락/);assert.doesNotMatch(g.text,/30%|20%|아이템별 변경/);assert.equal(g.items,undefined);assert.deepEqual(g.versions,['v12']);});
test('different monster items use category union and per-monster counts; mixed grades omitted',()=>{const a=member('1'),b=member('2',.1);b.changes[0].itemId='41';b.changes[0].grade=5;b.changes.push({...change(),itemId:'42',grade:5});const g=groupSummaries([a,b])[0];assert.equal(g.uniformGrade,null);assert.equal(g.rollups[0].itemCount,3);assert.equal(g.rollups[0].perMonsterMin,1);assert.equal(g.rollups[0].perMonsterMax,2);assert.doesNotMatch(g.text,/희귀|영웅/);assert.match(g.text,/몬스터별 1–2종/);});
test('mixed directions and subset changes stay separate without assuming all monsters share them',()=>{const a=member('1'),b=member('2');b.changes[0].direction='increase';const g=groupSummaries([a,b])[0];assert.equal(g.rollups.length,2);assert.match(g.rollups[0].sentence,/2종 중 1종/);assert.match(g.rollups[1].sentence,/2종 중 1종/);assert.equal(g.rollups[0].itemCount,1);assert.equal(g.rollups[1].itemCount,1);});
test('unknown grade suppresses category grade and quantities remain distinct from probability',()=>{const a=member('1'),b=member('2');b.changes[0].grade=null;a.changes[0].quantityChanged=true;a.changes[0].quantityDirection='decrease';const g=groupSummaries([a,b])[0];assert.equal(g.uniformGrade,null);assert.doesNotMatch(g.text,/희귀 등급/);assert.equal(g.rollups.find(r=>r.kind==='quantityDown').monsterCount,1);});
test('same unique number with different maps, hunting areas or NPC types is not merged',()=>{for(const key of ['map','area','npcType']){const a=member('1'),b=member('2');b.monster[key]='다른 값';assert.equal(groupSummaries([a,b]).length,2);}});
test('Temp NPC metadata chooses v12 over v9 and overrides ability map',()=>{
 const source={sheet:'(Temp)NPC_Info',row:5,version:'v12'},rows=selectLatest([{id:'1',v:12,map:'최신 배치 맵',area:'최신 사냥터',npcType:'엘리트',uniqueNumber:'최신',displayLevel:'120',source},{id:'1',v:9,map:'과거 맵',source:{...source,version:'v9'}}],'NPC',[]);
 const d={format:1,tables:{infos:[],npcs:[{id:'1',abilityId:'1'}],abilities:[{id:'1',dropId:'0'}],abilityNames:[{id:'1',map:'능력치 맵'}],npcNames:rows}};
 const m=makeDropIndex(d).search('1').rows[0];assert.equal(m.map,'최신 배치 맵');assert.equal(m.area,'최신 사냥터');assert.equal(m.npcType,'엘리트');assert.equal(m.displayLevel,'120');assert.equal(m.classificationSource.version,'v12');
 rows[0].conflict=true;const broken=makeDropIndex(d).search('1').rows[0];assert.equal(broken.uniqueNumber,'');assert.equal(broken.classificationConflict,true);
});
